name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths:
    - 'apps/backend/**'
  pull_request:
    branches: ["main"]
    paths:
    - 'apps/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag lumoflo-backend:${{ github.sha }} --tag lumoflo-backend:latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag lumoflo-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/lumoflo-backend:${{ github.sha }}
          docker tag lumoflo-backend:latest ghcr.io/${{ github.repository_owner }}/lumoflo-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/lumoflo-backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/lumoflo-backend:latest
